data:
  raw: "data/raw/dataset.csv"
  processed: "data/processed/dataset_processed.csv"
  interim: "data/interim/"
  external: "data/external/"
  dvc_remote: "github"

models:
  dir: "models/"

mlflow:
  tracking_uri: "mlruns"
